# Generated by Django 3.2.12 on 2026-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_wordlist',
            name='path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
