# Generated by Django 3.2.12 on 2026-01-03 12:53

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Downloader', '0002_alter_upload_wordlist_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_wordlist',
            name='file',
            field=models.FileField(upload_to=app.models.setFilePath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'list'])]),
        ),
    ]
